# Generated by Django 4.2.4 on 2023-09-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('flname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('foundationdate', models.DateField()),
                ('website', models.CharField(max_length=500)),
            ],
        ),
    ]
