# Generated by Django 4.1.11 on 2023-09-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_provider_user_alter_provider_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
    ]
